accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^register/$', views.register, {'template_name': 'registration/register.html'}, name='register'),
    url(r'^my_account/$', views.my_account, {'template_name': 'registration/register.html'}, name='my_account'),
    url(r'^order_info/$', views.order_info, {'template_name': 'registration/order_info.html'}, name='order_info'),
    url(r'^order_details/(?P<order_id>[-\w]+)/$', views.order_details,
        {'template_name': 'registration/order_details.html'}, name='order_details'),
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout')
]

cart/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.show_cart, {'template_name': 'cart/cart.html'}, name='show_cart'),
]

catalog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from catalog import views

urlpatterns = [
    url(r'^$', views.index, {'template_name': 'catalog/index.html'}, name='catalog_home'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.show_category, {'template_name': 'catalog/category.html'},
        name='catalog_category'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', views.show_product, {'template_name': 'catalog/product.html'},
        name='catalog_product'),
    url(r'^review/product/add/$', csrf_exempt(views.add_review), name='add_review'),
    url(r'^tag/product/add/$', csrf_exempt(views.add_tag), name='add_tag'),
    url(r'^tag_cloud/$', views.tag_cloud,  {'template_name': 'catalog/tag_cloud.html'}, name='tag_cloud'),
    url(r'^tag/(?P<tag>[-\w]+)/$', views.tag,  {'template_name': 'catalog/tag.html'}, name='tag'),
]

ecomstore/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^', include('catalog.urls', namespace='catalog')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^pay/', include('pay.urls', namespace='pay')),
    url(r'^', include('marketing.urls', namespace='marketing')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'ecomstore.views.file_not_found_404'

pay/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^pay/$', views.pay, name='pay'),
]

search/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^results/$', views.results, {'template_name': 'search/results.html'}, name='search_results'),
]

templates/tags/cart_box.html
{% with cart_item_count as count %}
    {% url 'cart.views.show_cart' as show_cart %}
    <a href="{{ show_cart }}">
        Shopping Cart
        <br/>
        {{ count }} Item{{ count|pluralize }}
    </a>
{% endwith %}

templates/tags/category_list.html
<h3>Categories</h3>
<ul id="categories">

{% with active_categories as cats %}
    {% for c in cats %}
        <li>
        {% ifequal c.get_absolute_url request_path %}
        {{ c.name }}<br />
        {% else %}
        <a href="{{ c.get_absolute_url }}" class="category">{{ c.name }}</a><br />
        {% endifequal %}
        </li>
    {% endfor %}
{% endwith %}

</ul>

templates/tags/footer.html
<a href="{% url 'catalog:catalog_home' %}">Home</a>
    {% with flatpage_list as pages %}
        {% for page in pages %}
            <a href="{{ page.url }}">{{ page.title }}</a>
        {% endfor %}
    {% endwith %}
<a href="{% url 'cart:show_cart' %}">Shopping Cart</a>

templates/tags/form_table_row.html
<tr>
    <th>
    {% if form_field.field.required %}*{% endif %}
    {{ form_field.label_tag }}
    </th>
    <td>
    {% if form_field.errors %}
        <ul class="errorlist">
        {% for error in form_field.errors %}
            <li>{{ form_field.label }}: {{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}

    {{ form_field }}
    </td>
</tr>

templates/tags/navigation.html
<ul>
	<li><a href="{% url 'catalog:catalog_home' %}">Home</a></li>
	<li><a href="/about/">About</a></li>
	<li><a href="/privacy-policy/">Privacy</a></li>
	<li><a href="/products/">Products</a></li>
	<li><a href="/contact/">Contact</a></li>
 	<li>
        <a href="{% url 'accounts:my_account' %}">My Account</a>
    </li>
</ul>
<div class="fr">
<ul>
    <li>
        {% if user.is_authenticated %}
            {% url 'accounts:logout' as logout_url %}
            <a href="{{ logout_url }}">Logout</a>
        {% else %}
            {% url 'accounts:register' as register_url %}
            <a href="{{ register_url }}">Sign Up</a>
            </li>
            <li>
            {% url 'accounts:login' as login_url %}
            <a href="{{ login_url }}">Login</a>
        {% endif %}
    </li>
</ul>
</div>
<div class="cb"></div>

templates/tags/pagination_links.html
{% if p.has_other_pages %}
    {% if p.has_previous %}
        <a href="{{ request.path }}?{{ params }}&page={{ p.previous_page_number }}">&laquo; Previous</a>
    {% else %}
        &laquo; Previous
    {% endif %}

    | Page {{ p.number }} of {{ paginator.num_pages }} |

    {% if p.has_next %}
        <a href="{{ request.path }}?{{ params }}&page={{ p.next_page_number }}">Next &raquo;</a>
    {% else %}
        Next &raquo;
    {% endif %}
{% endif %}

templates/tags/product_list.html
{% for p in products %}
    {% if forloop.first %}
        <h3>{{ header_text }}</h3>
    {% endif %}
    {% include 'tags/product_thumbnail.html' %}
    {% if forloop.last %}
        <div class="cb">&nbsp;</div>
    {% endif %}
{% endfor %}

templates/tags/product_thumbnail.html
<div class="product_thumbnail">
    <a href="{{ p.get_absolute_url }}">
        <img src="{{ p.thumbnail.url }}" alt="{{ p.name }}" class="bn" />
        <br />
        {{ p.name }}
    </a>
</div>

templates/tags/search_box.html
<form id="search" action="{% url 'search:search_results' %}" method="get">
<h3><label for="id_q">Search</label></h3>
    <div style="text-align:right;">
    {{ form.q }}
        <input type="submit" value="Search" />
    </div>
</form>