accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^register/$', views.register, {'template_name': 'registration/register.html'}, name='register'),
    url(r'^my_account/$', views.my_account, {'template_name': 'registration/register.html'}, name='my_account'),
    url(r'^order_info/$', views.order_info, {'template_name': 'registration/order_info.html'}, name='order_info'),
    url(r'^order_details/(?P<order_id>[-\w]+)/$', views.order_details,
        {'template_name': 'registration/order_details.html'}, name='order_details'),
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout')
]

catalog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from catalog import views

urlpatterns = [
    url(r'^$', views.index, {'template_name': 'catalog/index.html'}, name='catalog_home'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.show_category, {'template_name': 'catalog/category.html'},
        name='catalog_category'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', views.show_product, {'template_name': 'catalog/product.html'},
        name='catalog_product'),
    url(r'^review/product/add/$', csrf_exempt(views.add_review), name='add_review'),
    url(r'^tag/product/add/$', csrf_exempt(views.add_tag), name='add_tag'),
    url(r'^tag_cloud/$', views.tag_cloud,  {'template_name': 'catalog/tag_cloud.html'}, name='tag_cloud'),
    url(r'^tag/(?P<tag>[-\w]+)/$', views.tag,  {'template_name': 'catalog/tag.html'}, name='tag'),
]

ecomstore/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^', include('catalog.urls', namespace='catalog')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^pay/', include('pay.urls', namespace='pay')),
    url(r'^', include('marketing.urls', namespace='marketing')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'ecomstore.views.file_not_found_404'

pay/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^pay/$', views.pay, name='pay'),
]

catalog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from catalog.managers import (ActiveCategoryManager, ActiveProductManager,
                              ActiveProductReviewManager,
                              FeaturedProductManager)
from tagging.registry import register


# Create your models here.
class Category(models.Model):
    """
    商品类别
    """
    objects = models.Manager()
    active = ActiveCategoryManager()

    name = models.CharField(_(u'类别名称'), max_length=50)
    slug = models.SlugField(_(u'slug'), max_length=50, unique=True,
                            help_text='Unique value for product page URL, created automatically from name.')
    description = models.TextField(_(u'类别描述'))
    is_active = models.BooleanField(_(u'状态'), default=True)
    meta_keywords = models.CharField(_(u'SEO关键字'), max_length=50,
                                     help_text='Comma-delimited set of SEO keywords for keywords meta tag')
    meta_description = models.CharField(_(u'SEO描述'), max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateField(_(u'创建时间'), auto_now_add=True)
    updated_at = models.DateField(_(u'更新时间'), auto_now=True)

    class Meta:
        db_table = 'categories'
        ordering = ['-created_at', ]
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:catalog_category', kwargs={"category_slug": self.slug})


class Product(models.Model):
    """
    商品
    """
    objects = models.Manager()
    active = ActiveProductManager()
    featured = FeaturedProductManager()

    name = models.CharField(_(u'商品名称'), max_length=255, unique=True)
    slug = models.SlugField(_(u'slug'), max_length=255, unique=True,
                            help_text='Unique value for product page URL, created automatically from name.')
    brand = models.CharField(_(u'品牌名称'), max_length=50)
    sku = models.CharField(_(u'存货量'), max_length=50)
    price = models.DecimalField(_(u'当前价格'), max_digits=9, decimal_places=2)
    old_price = models.DecimalField(_(u'历史价格'), max_digits=9, decimal_places=2, blank=True, default=0.00)
    image = models.ImageField(_(u'商品图片大图'), upload_to='images/products/main')
    thumbnail = models.ImageField(_(u'商品图片缩略图'), upload_to='images/products/thumbnails')
    image_caption = models.CharField(_(u'商品图片标题'), max_length=200)
    is_active = models.BooleanField(_(u'状态'), default=True)
    is_bestseller = models.BooleanField(_(u'畅销商品'),  default=False)
    is_featured = models.BooleanField(_(u'特色商品'), default=False)
    quantity = models.IntegerField(_(u'数量'))
    description = models.TextField(_(u'描述'))
    meta_keywords = models.CharField(_(u'SEO关键字'), max_length=50,
                                     help_text='Comma-delimited set of SEO keywords for keywords meta tag')
    meta_description = models.CharField(_(u'SEO描述'), max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateField(_(u'创建时间'), auto_now_add=True)
    updated_at = models.DateField(_(u'更新时间'), auto_now=True)
    categories = models.ManyToManyField(Category)

    class Meta:
        db_table = 'products'
        ordering = ['-created_at', ]

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:catalog_product', kwargs={"product_slug": self.slug})

    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None

    # user recommendation part
    def cross_sells(self):
        """
        gets other Product instances that have been combined with the current instance in past orders.
        Includes the orders that have been placed by anonymous users that haven't registered
        """
        from checkout.models import Order, OrderItem
        orders = Order.objects.filter(orderitem__product=self)
        order_items = OrderItem.objects.filter(order__in=orders).exclude(product=self)
        products = Product.active.filter(orderitem__in=order_items).distinct()
        return products

    # users who purchased this product also bought....
    def cross_sells_user(self):
        """
        gets other Product instances that have been ordered by other registered customers who also ordered the current
        instance. Uses all past orders of each registered customer and not just the order in which the current
        instance was purchased
        """
        from checkout.models import Order, OrderItem
        users = User.objects.filter(order__orderitem__product=self)
        items = OrderItem.objects.filter(order__user__in=users).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        return products

    def cross_sells_hybrid(self):
        """
        gets other Product instances that have been both been combined with the current instance in orders placed by
        unregistered customers, and all products that have ever been ordered by registered customers
        """
        from checkout.models import Order, OrderItem
        from django.db.models import Q
        orders = Order.objects.filter(orderitem__product=self)
        users = User.objects.filter(order__orderitem__product=self)
        items = OrderItem.objects.filter(Q(order__in=orders) |
                                         Q(order__user__in=users)
                                         ).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        return products


class ProductReview(models.Model):
    """
    model class containing product review data associated with a product instance
    """
    RATINGS = ((5, 5), (4, 4), (3, 3), (2, 2), (1, 1),)

    product = models.ForeignKey(Product)
    user = models.ForeignKey(User)
    title = models.CharField(_(u'标题'), max_length=50)
    date = models.DateTimeField(_(u'创建时间'), auto_now_add=True)
    rating = models.PositiveSmallIntegerField(_(u'评分'), default=5, choices=RATINGS)
    is_approved = models.BooleanField(_(u'通过'), default=True)
    content = models.TextField(_(u'内容'), )

    objects = models.Manager()
    approved = ActiveProductReviewManager()

register(Product)

catalog/forms.py
# -*- coding: utf-8 -*-
from django import forms

from catalog.models import Product, ProductReview


# Create your forms here.
class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_price(self):
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError('Price must be greater than zero.')
        return self.cleaned_data['price']


# 添加购物车表单
class ProductAddToCartForm(forms.Form):
    quantity = forms.IntegerField(
            widget=forms.TextInput(attrs={'size': '2', 'value': '1', 'class': 'quantity', 'maxlength': '5'}),
            error_messages={'invalid': 'Please enter a valid quantity.'},
            min_value=1)
    product_slug = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ProductAddToCartForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Cookies must be enabled.")
        return self.cleaned_data


class ProductReviewForm(forms.ModelForm):
    """
    Form class to submit a new ProductReview instance
    """

    class Meta:
        model = ProductReview
        exclude = ('user', 'product', 'is_approved')

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import Context
from django.template.loader import get_template

from cart import carts
from catalog.forms import ProductAddToCartForm, ProductReviewForm
from catalog.models import Category, Product, ProductReview
from stats import stats

from tagging import utils
from tagging.models import Tag, TaggedItem


# Create your views here.
def index(request, template_name="catalog/index.html"):
    search_recs = stats.recommended_from_search(request)
    featured = Product.featured.all()[0:settings.PRODUCTS_PER_ROW]
    recently_viewed = stats.get_recently_viewed(request)
    view_recs = stats.recommended_from_views(request)

    page_title = 'Musical Instruments and Sheet Music for Musicians'

    return render(request, template_name, locals())


def show_category(request, category_slug, template_name="catalog/category.html"):
    c = get_object_or_404(Category, slug=category_slug)
    product = c.product_set.all()
    page_title = c.name
    meta_keywords = c.meta_keywords
    meta_description = c.meta_description
    return render(request, template_name, context=locals())


def show_product(request, product_slug, template_name="catalog/product.html"):
    p = get_object_or_404(Product, slug=product_slug)
    categories = p.categories.filter(is_active=True)
    page_title = p.name
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description

    if request.method == 'POST':
        # add to cart
        post_data = request.POST.copy()
        form = ProductAddToCartForm(request, post_data)
        if form.is_valid():
            # add to cart and redirect to cart page
            carts.add_to_cart(request)
            # if test cookie worked, get rid of it
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            return redirect('cart:show_cart')
    else:
        form = ProductAddToCartForm(request=request, label_suffix=':')
    # assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
    # set the test cookie on our first GET request
    request.session.set_test_cookie()
    stats.log_product_view(request, p)
    # product review
    product_reviews = ProductReview.approved.filter(product=p).order_by('-date')
    review_form = ProductReviewForm()

    return render(request, template_name, context=locals())


@login_required
def add_review(request):
    """
    AJAX view that takes a form POST from a user submitting a new product review;
    requires a valid product slug and args from an instance of ProductReviewForm;
    return a JSON response containing two variables: 'review', which contains
    the rendered template of the product review to update the product page,
    and 'success', a True/False value indicating if the save was successful.
    """
    form = ProductReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        slug = request.POST.get('slug')
        product = Product.active.get(slug=slug)
        review.user = request.user
        review.product = product
        review.save()

        template = "catalog/product_review.html"
        t = get_template(template)
        html = t.render(Context({'review': review}))
        response = {'success': 'True', 'html': html}

    else:
        html = form.errors.as_ul()
        response = {'success': 'False', 'html': html}
    return JsonResponse(response)


@login_required
def add_tag(request):
    """
    AJAX view that takes a form POST containing variables for a new product tag;
    requires a valid product slug and comma-delimited tag list; returns a JSON response
    containing two variables: 'success', indicating the status of save operation, and 'tag',
    which contains rendered HTML of all product pages for updating the product page.
    """
    tags = request.POST.get('tag', '')
    slug = request.POST.get('slug', '')
    if len(tags) > 2:
        p = Product.active.get(slug=slug)
        html = u''
        template = "catalog/tag_link.html"
        t = get_template(template)
        for tag in tags.split():
            tag.strip(',')
            Tag.objects.add_tag(p, tag)
        for tag in p.tags:
            html += t.render(Context({'tag': tag}))
        response = {'success': 'True', 'html': html}
    else:
        response = {'success': 'False'}
    return JsonResponse(response, safe=False)


def tag_cloud(request, template_name="catalog/tag_cloud.html"):
    """
    view containing a list of tags for active products, sized proportionately by relative
    frequency
    """
    product_tags = Tag.objects.cloud_for_model(Product, steps=9,
                                               distribution=utils.LOGARITHMIC,
                                               filters={'is_active': True})
    page_title = 'Product Tag Cloud'
    return render(request, template_name, locals())


def tag(request, tag, template_name="catalog/tag.html"):
    """
    view listing products that have been tagged with a given tag
    """
    products = TaggedItem.objects.get_by_model(Product.active, tag)
    page_title = 'Products tagged with ' + tag
    return render(request, template_name, locals())

templates/catalog/category.html
{% extends "catalog.html" %}

{% block content %}
    <h1>{{ c.name }}</h1>
    {{ c.description }}
    <br /><br />
    {% for p in products %}
        {% include 'tags/product_thumbnail.html' %}
{#        <div class="product_thumbnail">#}
{#            <a href="{{ p.get_absolute_url }}">#}
{#                <img src="{{ p.image.url }}" alt="{{ p.name }}" class="bn"/>#}
{#                <br />#}
{#                {{ p.name }}#}
{#            </a>#}
{#        </div>#}
    {% endfor %}
{% endblock %}

templates/catalog/index.html
{% extends "catalog.html" %}

{% load catalog_tags %}

{% block content %}
<h1>Welcome to Modern Musician!</h1>

{% product_list recently_viewed 'Your Recently Viewed' %}
{% product_list view_recs 'Similar Products' %}
{% product_list featured 'Featured Products' %}
{% product_list search_recs 'Recommended For You' %}

{% endblock %}

templates/catalog/product.html
{% extends "catalog.html" %}

{% block content %}
    <div class="product_image">
        <img src="{{ p.image.url }}" alt="{{ p.name }}" />
        <br />
        {{ p.image_caption }}
    </div>
    <h1>{{ p.name }}</h1>
    Brand: <em>{{ p.brand }}</em>
    <br /><br />
    SKU: {{ p.sku }}
    <br />
    In category{{ categories.count|pluralize:"y,ies" }}:
    {% for c in categories %}
        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
    <br /><br />
    {% if p.sale_price %}
        Was: <del>$ {{ p.old_price }}</del>
        <br />
        Now: $ {{ p.price }}
    {% else %}
        Price: $ {{ p.price }}
    {% endif %}
    <br /><br />
    <form method="post" action="." class="cart">
        {% csrf_token %}
        {{ form.as_p }}
        <br />
        <input type="submit" value="Add to Cart" name="submit" alt="Add to Cart" />
    </form>
    <div class="cb"><br /><br /></div>
    <h3>Related Products</h3>
        {% for p in p.cross_sells_hybrid %}
            {% include 'tags/product_thumbnail.html' %}
        {% empty %}
            No related products.
        {% endfor %}
    <div class="cb"><br /><br /></div>
    <h3>Product Description</h3>
        {{ p.description }}
    {#  tag part  #}
    <div class="cb"><br /><br /></div>
    <h3>Product Tags</h3>

    <div id="tags">
        {% for tag in p.tags %}
            {% include 'catalog/tag_link.html' %}
        {% endfor %}
    </div>
    <br />
    {% if request.user.is_authenticated %}
        <label for="id_tag">Tag this product (must be at least three characters):</label>
        <br />
        <input id="id_tag" type="text" />
        <input type="submit" value="Tag It" id="add_tag" />

    {% else %}
        {% url 'accounts:login' as login_url %}
        <a href="{{ login_url }}?next={{ request.path }}">
            Log in to tag this product.
        </a>
    {% endif %}
{#  review part  #}
    <div class="cb"><br /><br /></div>
    <h3>Product Reviews</h3>
        {% if request.user.is_authenticated %}
        <a id="add_review">Write a Review</a>
    <div id="review_form">
        <div id="review_errors"></div>
        <table>
        {{ review_form.as_table }}
        <tr><td colspan="2">
            <input type="hidden" id="id_slug" value="{{ p.slug }}" />
            <input type="submit" id="submit_review" value="Submit" />
            <input type="submit" id="cancel_review" value="Cancel" />
        </td></tr>
        </table>
    </div>
        {% else %}
            {% url 'accounts:login' as login_url %}
            <a href="{{ login_url }}?next={{ request.path }}">
                Log in to write your own review.
            </a>
        {% endif %}

    <div class="cb"><br /><br /></div>

    <div id="reviews">
        {% for review in product_reviews %}
            {% include 'catalog/product_review.html' %}
        {% empty %}
            <div id="no_reviews">
                No product reviews yet.
            </div>
        {% endfor %}
    </div>
    <div class="cb"><br /><br /></div>
{% endblock %}

templates/catalog/product_review.html
<div class="review">
    Rating: {{ review.rating }}
    <strong>{{ review.title }}</strong>
    by {{ review.user.username }}
    <br />
    {{ review.content }}
    <br /><br />
    <hr />
</div>

templates/catalog/tag.html
{% extends "catalog.html" %}

{% block content %}
    <h1>Products tagged with: '{{ tag }}'</h1>
    {% for p in products %}
        {% include 'tags/product_thumbnail.html' %}
    {% endfor %}
{% endblock %}

templates/catalog/tag_cloud.html
{% extends "catalog.html" %}

{% load tagging_tags %}

{% block content %}
    <h1>Product Tag Cloud</h1>
    {% for tag in product_tags %}
        <a href="/tag/{{ tag.name }}/" style="font-size: {{ tag.font_size|add:"11" }}px;">{{ tag.name|slugify }}</a>&nbsp;
    {% endfor %}
{% endblock %}

templates/catalog/tag_link.html
<a href="/tag/{{ tag.name }}/">{{ tag.name|slugify }}</a>&nbsp;